### ISSUE TITLE
when i use it to build apk, it's very slow. how can i resolve this?

### ISSUE THREAD

**Issue by leasual** [WindSekirun/Jenkins-Android-Docker#5]
when i use it to build apk, it's very slow. how can i resolve this?

**Comment by WindSekirun** [comment]
This issue is likely to be affecting server performance, not docker image issues.

Currently, I using [Vultr VPS - High Frequency Compute $12/month options](https://www.vultr.com/products/high-frequency-compute/) to build apk and it takes 3 min to build apk. 

So, please consider upgrading your server and change parameters which affect build speed (Java heap size, multiDexEnabled with minSdk 21... There are many way to optimize build speed.)

**Comment by leasual** [comment]
@WindSekirun Thanks, i will have a try.
